version: 2
jobs:
  build:
    resource_class: xlarge
    docker:
      - image: marcomorain/android:0.13
    environment:
      QEMU_AUDIO_DRV: none
      TERM: dumb
      #     ADB_TRACE: all
      _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run: nohup ./gradlew
      - run:
          name: Start Emulator
          command: |
            env
            echo done env
            java -version
            avdmanager create avd --name pixel --device pixel --tag google_apis --package 'system-images;android-25;google_apis;armeabi-v7a'
            #emulator -memory 256 -verbose -no-boot-anim -gpu swiftshader -no-audio -no-window -avd pixel
            emulator -verbose -gpu swiftshader -no-audio -no-window -avd pixel
          background: true
      - run:
          name: Wait for simulator
          command: circle-android wait-for-boot
      - run:
          name: Logcat
          command: adb logcat
          background: true
      - restore_cache:
          key: cache-7-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Compile
          command: ./gradlew assemble assembleAndroidTest -PdisablePreDex
      - save_cache:
          key: cache-7-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.m2
            - ~/.android/cache/
            - ~/.gradle
      - run:
          name: Wake Simulator
          command: |
            trap "echo trapped; ps aux --sort -rss; exit" SIGHUP SIGINT SIGTERM SIGKILL
            echo -- Devices
            adb devices -l
            echo -- PS
            ps aux --sort -rss
            echo -- Key Event
            adb shell input keyevent 82
            echo -- Screen timeout
            adb shell settings put system screen_off_timeout 600000

      - run:
          name: Test on Device
          command: ./gradlew connectedAndroidTest
          no_output_timeout: 60m
          environment:
            ADB_TRACE: all
        #- run: adb shell am instrument -w -r -e debug false -e class com.circleci.demoapplication.ExampleInstrumentedTest#shouldFail com.circleci.demoapplication.test/android.support.test.runner.AndroidJUnitRunner
        #  adb push app/build/outputs/apk/app-debug-androidTest.apk /data/local/tmp/com.circleci.demoapplication.test
        #- run:
        #  command: adb shell pm install -r /data/local/tmp/com.circleci.demoapplication.test
        #  no_output_timeout: 30m
        #  environment:
        #    ADB_TRACE: all
        #- run: adb shell am instrument -w -r -e debug false -e class com.circleci.demoapplication.ExampleInstrumentedTest#shouldFail com.circleci.demoapplication.test/android.support.test.runner.AndroidJUnitRunner


