version: 2
jobs:
  build:
    docker:
      - image: circlec/android:api-25-alpha
    environment:
      _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    steps:
      - checkout
      - run:
          name: Compile
          command: ./gradlew assemble assembleAndroidTest -PdisablePreDex
      - save_cache:
          key: cache-7-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.m2
            - ~/.android/cache/
            - ~/.gradle


