version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-7-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - cache-7-
      - run: ./gradlew tasks
      - run:
          name: Compile
          command: ./gradlew assemble assembleAndroidTest -PdisablePreDex
      - save_cache:
          key: cache-7-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
          paths:
            - ~/.m2
            - ~/.android/cache/
            - ~/.gradle
      


